---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canary-test-v1
  name: canary-test-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-test-v1
  template:
    metadata:
      labels:
        app: canary-test-v1
    spec:
      containers:
      - image: simbu1290/nginx-canary-test:v1
        name: nginx-canary-test
        ports:
        - name: http
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: canary-test-v1
  name: canary-test-v1
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: canary-test-v1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-test-v1
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: canary-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canary-test-v1
            port:
              number: 5000
