apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mysql-pv
  resources:
    requests:
      storage: 2Gi
